name: build and push docker image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build image
        run: |
          docker buildx build --push \
            --tag "${{ secrets.DOCKER_USER }}/ps2runner:latest" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
